### ISSUE TITLE
Use next.js 10 @hookform/resolvers yup to get the following error SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by jq153387** [react-hook-form/resolvers#105]
SyntaxError: Cannot use import statement outside a module

Use next.js 10 @hookform/resolvers yup to get the following error

![截圖 2021-01-04 下午11 07 10](https://user-images.githubusercontent.com/11733606/103549064-c1257e00-4ee1-11eb-953b-2cf114209242.png)
```
import { transformToNestObject, } from 'react-hook-form';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/jq153387/Sites/test/node_modules/@hookform/resolvers/yup.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at eval (webpack-internal:///@hookform/resolvers/yup:1:18)
    at Object.@hookform/resolvers/yup (/Users/jq153387/Sites/test/.next/server/pages/index.js:115:1)
/Users/jq153387/Sites/test/node_modules/@hookform/resolvers/dist/yup.js:2
```
----
```
"dependencies": {
    "@hookform/resolvers": "^1.3.1",
    "next": "^10.0.4",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-hook-form": "^6.14.0",
    "yup": "^0.32.8"
  },
```

**Comment by jorisre** [comment]
Same as https://github.com/react-hook-form/resolvers/issues/100

I'm working on resolvers's V2 which will have a better bundle supports.
As a workaround, you can use 1.3.0

**Comment by la55u** [comment]
I have the exact same issue but with `zod`

**Comment by jq153387** [comment]
@jorisre Using 1.3.0 is the same situation, other versions 1.2.0 ~ 1.0.0 have been tried, all in the same situation. do not know why?

**Comment by la55u** [comment]
@jorisre 1.3.0 works, make sure you use the exact version and not ^1.3.0.

**Comment by jq153387** [comment]
@la55u Thank you so much, I don't quite understand the difference between 1.3.0 and ^1.3.0? @

**Comment by pau1tuck** [comment]
@jq153387 **yarn add @hookform/resolvers@1.3.0** (exact version) fixes the issue for me. If you use the caret ^ it means there could be a minor patch, e.g. 1.3.1, which doesn't work here.

**Comment by jorisre** [comment]
@pau1tuck The issue is solved, you can use the latest version [v1.3.6](https://github.com/react-hook-form/resolvers/releases/tag/v1.3.6)

**Comment by ElektrikSpark** [comment]
I am getting this error in `"next": "12.0.7"` witrh `"@hookform/resolvers": "^2.8.4"`

**Comment by FlorianCassayre** [comment]
Make sure you are importing:
```js
import { zodResolver } from '@hookform/resolvers/zod';
```
and not:
```js
import { zodResolver } from '@hookform/resolvers/zod/dist/zod';
```
That was my problem (the IDE picked this import for some reason).
