### ISSUE TITLE
Imports not works since version 2.8.4 or 2.8.3

### ISSUE THREAD

**Issue by yangricardo** [react-hook-form/resolvers#337]
**Describe the bug**
Hi, i have a NextJS application implemented with typescript that uses the yupResolver from this library. 
I have several deployments on Vercel and Heroku platforms that  does not find the module.

Also, i have never imported successfuly using `import { yupResolver } from '@hookform/resolvers/yup';` statement, by the way, for production deployments i have always used `import { yupResolver } from '@hookform/resolvers/yup/dist/yup';`. 

Rollback and freezing the version for `2.8.3` has worked sucessfully, but as i can see, import the resolvers has always been shown to have issues.

I can not reproduce in a sandbox now, as it involves some proprietary code, but was kind hard to discover in my application that the issue involved the yupResolver by showing the following error

```
<html>
<body>
<!--StartFragment-->

Error occurred prerendering page "/cms/campaigns/new". Read more: https://nextjs.org/docs/messages/prerender-error
--
10:28:55.260 | ReferenceError: Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization
10:28:55.260 | at Object.Z (/vercel/path0/.next/server/chunks/3705.js:3505:36)
10:28:55.260 | at NewCampaignProfile (/vercel/path0/.next/server/pages/cms/campaigns/new.js:37:165)
10:28:55.260 | at d (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
10:28:55.261 | at bb (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
10:28:55.261 | at a.b.render (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
10:28:55.261 | at a.b.read (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
10:28:55.261 | at Object.exports.renderToString (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
10:28:55.261 | at renderPage (/vercel/path0/node_modules/next/dist/server/render.js:723:46)
10:28:55.261 | at Object.ctx.renderPage (/vercel/path0/.next/server/pages/_document.js:71:30)
10:28:55.261 | at Object.defaultGetInitialProps (/vercel/path0/node_modules/next/dist/server/render.js:364:51)

<!--EndFragment-->
</body>
</html>
```

This similar error has been reproduced across many other modules, as those NextJS page has a built in a implementation of react hook form in a footer component. After that, i have been isolating a lot of code until get a error that crashed in production execution.

Some errors have mention that resolvers implementation were not available to be used with CommonJS implementation, so i recommend to check if those resolvers exports are correctly to be used by typescript code.

**Comment by bluebill1049** [comment]
Can you use the latest version?

**Comment by yangricardo** [comment]
> Can you use the latest version?

No, i have tried all versions after `2.8.3`. As i said, even on `2.8.3` i had to import in different way as shown in the docs. It's seems to be a Typescript module export definition issue..

**Comment by bluebill1049** [comment]
what's your nextjs version?

**Comment by yangricardo** [comment]
> what's your nextjs version?

NextJS Version: 12.0.9
I'll put here all the dependencies i use currently and the tsconfig

> package.json dependencies and dev dependencies
```json
"dependencies": {
    "@apollo/client": "^3.4.13",
    "@hookform/resolvers": "2.8.3",
    "@stripe/react-stripe-js": "^1.4.1",
    "@stripe/stripe-js": "^1.18.0",
    "@tailwindcss/forms": "^0.3.4",
    "@tinymce/tinymce-react": "^3.13.0",
    "@types/react-input-mask": "^3.0.1",
    "@unform/core": "^2.1.6",
    "@unform/web": "^2.1.6",
    "antd": "^4.17.3",
    "autoprefixer": "^10.3.4",
    "axios": "^0.21.4",
    "carousel": "^0.0.3",
    "cookie": "^0.4.1",
    "cpf-cnpj-validator": "^1.0.3",
    "daisyui": "^1.16.1",
    "date-fns": "^2.24.0",
    "date-fns-tz": "^1.1.6",
    "dotenv": "^10.0.0",
    "graphql": "^15.6.0",
    "i18next": "^21.0.1",
    "joi": "^17.5.0",
    "less": "^4.1.2",
    "less-loader": "^10.2.0",
    "localtunnel": "^2.0.2",
    "micro": "^9.3.4",
    "micro-cors": "^0.1.1",
    "next": "^12.0.8",
    "next-logger": "^3.0.0",
    "next-seo": "^4.28.1",
    "next-with-less": "^2.0.4",
    "postcss": "^8.3.6",
    "postcss-import": "^14.0.2",
    "postcss-preset-env": "^6.7.0",
    "react": "^17.0.2",
    "react-cookie": "^4.1.1",
    "react-dom": "^17.0.2",
    "react-dropzone": "^11.4.0",
    "react-hook-form": "^7.15.4",
    "react-i18next": "^11.12.0",
    "react-icons": "^4.2.0",
    "react-input-mask": "^2.0.4",
    "react-paginate": "^7.1.3",
    "react-password-strength-bar": "^0.3.5",
    "react-phone-input-2": "^2.14.0",
    "react-range": "^1.8.11",
    "react-select": "^4.3.1",
    "react-table": "^7.7.0",
    "react-toastify": "^8.0.2",
    "sharp": "^0.29.1",
    "showdown": "^1.9.1",
    "slugify": "^1.6.0",
    "socket.io": "^4.2.0",
    "socket.io-client": "^4.2.0",
    "stripe": "^8.184.0",
    "styled-components": "^5.3.1",
    "swiper": "^7.0.6",
    "tailwind.macro": "^0.5.10",
    "tailwindcss": "^2.2.19",
    "web-vitals": "^2.1.0",
    "yup": "^0.32.9"
  },
  "devDependencies": {
    "@hookform/devtools": "^4.0.1",
    "@tailwindcss/aspect-ratio": "^0.3.0",
    "@tailwindcss/line-clamp": "^0.2.2",
    "@tailwindcss/typography": "^0.4.1",
    "@types/gtag.js": "^0.0.8",
    "@types/i18next": "^13.0.0",
    "@types/micro": "^7.3.6",
    "@types/node": "^17.0.12",
    "@types/react": "^17.0.38",
    "@types/react-dom": "^17.0.11",
    "@types/react-i18next": "^8.1.0",
    "@types/react-icons": "^3.0.0",
    "@types/react-paginate": "^7.1.1",
    "@types/react-phone-number-input": "^3.0.13",
    "@types/react-select": "^4.0.17",
    "@types/react-table": "^7.7.4",
    "@types/showdown": "^1.9.4",
    "@types/styled-components": "^5.1.14",
    "babel-plugin-styled-components": "^1.13.2",
    "eslint": "<8.0.0",
    "eslint-config-next": "^12.0.8",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-react-hooks": "^4.2.0",
    "prettier": "^2.4.1",
    "react-phone-number-input": "^3.1.27",
    "tslib": "^2.3.1",
    "typescript": "^4.5.5"
  }
```
> tsconf.json
```json
{
  "compilerOptions": {
    /* Visit https://aka.ms/tsconfig.json to read more about this file */
    /* Basic Options */
    // "incremental": true /* Enable incremental compilation */,
    "target": "es6" /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', or 'ESNEXT'. */,
    "module": "commonjs" /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', 'es2020', or 'ESNext'. */,
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ] /* Specify library files to be included in the compilation. */,
    "allowJs": true /* Allow javascript files to be compiled. */,
    "checkJs": false /* Report errors in .js files. */,
    "jsx": "preserve" /* Specify JSX code generation: 'preserve', 'react-native', or 'react'. */,
    "declaration": true /* Generates corresponding '.d.ts' file. */,
    "declarationMap": true /* Generates a sourcemap for each corresponding '.d.ts' file. */,
    // "outFile": "./",                       /* Concatenate and emit output to single file. */
    // "outDir": "./build" /* Redirect output structure to the directory. */,
    // "rootDir": "./src" /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */,
    // "composite": true /* Enable project compilation */,
    // "tsBuildInfoFile": "./",               /* Specify file to store incremental compilation information */
    "removeComments": true /* Do not emit comments to output. */,
    // "noEmit": true /* Do not emit outputs. */,
    "importHelpers": true /* Import emit helpers from 'tslib'. */,
    "downlevelIteration": true /* Provide full support for iterables in 'for-of', spread, and destructuring when targeting 'ES5' or 'ES3'. */,
    "isolatedModules": true /* Transpile each file as a separate module (similar to 'ts.transpileModule'). */,
    /* Strict Type-Checking Options */
    "strict": true /* Enable all strict type-checking options. */,
    "noImplicitAny": true /* Raise error on expressions and declarations with an implied 'any' type. */,
    "strictNullChecks": true /* Enable strict null checks. */,
    "strictFunctionTypes": true /* Enable strict checking of function types. */,
    "strictBindCallApply": true /* Enable strict 'bind', 'call', and 'apply' methods on functions. */,
    "strictPropertyInitialization": false /* Enable strict checking of property initialization in classes. */,
    "noImplicitThis": true /* Raise error on 'this' expressions with an implied 'any' type. */,
    "alwaysStrict": true /* Parse in strict mode and emit "use strict" for each source file. */,
    /* Additional Checks */
    "noUnusedLocals": true /* Report errors on unused locals. */,
    "noUnusedParameters": true /* Report errors on unused parameters. */,
    "noImplicitReturns": true /* Report error when not all code paths in function return a value. */,
    "noFallthroughCasesInSwitch": true /* Report errors for fallthrough cases in switch statement. */,
    "noUncheckedIndexedAccess": true /* Include 'undefined' in index signature results */,
    /* Module Resolution Options */
    "moduleResolution": "node" /* Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6). */,
    "baseUrl": "./src/" /* Base directory to resolve non-absolute module names. */,
    "paths": {
      "@/*": [
        "./*"
      ]
    } /* A series of entries which re-map imports to lookup locations relative to the 'baseUrl'. */,
    // "rootDirs": ["./src"] /* List of root folders whose combined content represents the structure of the project at runtime. */,
    // "typeRoots": [] /* List of folders to include type definitions from. */,
    "types": [
      "tslib",
      "gtag.js"
    ] /* Type declaration files to be included in compilation. */,
    "allowSyntheticDefaultImports": true /* Allow default imports from modules with no default export. This does not affect code emit, just typechecking. */,
    "esModuleInterop": true /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */,
    "preserveSymlinks": true /* Do not resolve the real path of symlinks. */,
    // "allowUmdGlobalAccess": true,          /* Allow accessing UMD globals from modules. */
    /* Source Map Options */
    // "sourceRoot": "",                      /* Specify the location where debugger should locate TypeScript files instead of source locations. */
    // "mapRoot": "",                         /* Specify the location where debugger should locate map files instead of generated locations. */
    // "inlineSourceMap": true /* Emit a single file with source maps instead of having a separate file. */,
    // "inlineSources": true /* Emit the source alongside the sourcemaps within a single file; requires '--inlineSourceMap' or '--sourceMap' to be set. */,
    /* Experimental Options */
    "experimentalDecorators": true /* Enables experimental support for ES7 decorators. */,
    "emitDecoratorMetadata": true /* Enables experimental support for emitting type metadata for decorators. */,
    "resolveJsonModule": true,
    /* Advanced Options */
    "skipLibCheck": true /* Skip type checking of declaration files. */,
    "forceConsistentCasingInFileNames": true /* Disallow inconsistently-cased references to the same file. */,
    "noEmit": true,
    "incremental": true
  },
  "include": [
    "next-env.d.ts",
    "**/*.d.ts",
    "**/*.ts",
    "**/*.tsx",
    "**/*.js",
    "src/components/cards/card-auction.component",
    "src/hooks"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by bluebill1049** [comment]
NextJS Version: 12.0.9? it's not even released yet, right? I think this is probably an issue related to NextJS.

**Comment by bluebill1049** [comment]
related issue: https://github.com/react-hook-form/resolvers/issues/271

**Comment by evocateur** [comment]
`"preserveSymlinks": true` in the tsconfig is a potential red flag, although I'm not 100% confident.

`import { yupResolver } from '@hookform/resolvers/yup'` with `@hookform/resolvers@2.8.5` and `next@12.0.7` definitely works, can't speak to later versions or canary releases. Is there any custom config in `next.config.js` that could be changing the default ESM resolution behavior?

**Comment by bluebill1049** [comment]
thanks @evocateur for the tips 🙏

**Comment by yangricardo** [comment]
> NextJS Version: 12.0.9? it's not even released yet, right? I think this is probably an issue related to NextJS.

That's right, sorry for the mistype

**Comment by yangricardo** [comment]
> `"preserveSymlinks": true` in the tsconfig is a potential red flag, although I'm not 100% confident.
> 
> `import { yupResolver } from '@hookform/resolvers/yup'` with `@hookform/resolvers@2.8.5` and `next@12.0.7` definitely works, can't speak to later versions or canary releases. Is there any custom config in `next.config.js` that could be changing the default ESM resolution behavior?

I'm going to try that. About the `next.config.js` that's the current state:

```
const withLess = require("next-with-less");

module.exports = withLess({
  i18n,
  reactStrictMode: true,
  webpack5: true,
  images: {
    domains: ["", "/", "s3.us-west-1.amazonaws.com", "media.giphy.com"]
  }
})
```

**Comment by yangricardo** [comment]
> related issue: #271

That's really similar. I have tried to put `"preserveSymlinks": true`  in `tsconfig.json` without success. 
I think is some NextJS 12 module resolution mismatch.
For now, i'm freezing this library at `2.8.3` version and importing `@hookform/resolvers/yup/dist/yup`

**Comment by yangricardo** [comment]
> related issue: #271

FIY, when i run build, with latest version and `"preserveSymlinks": false`, it displayed some logs mentioned on #271 

```
> Build error occurred
file:///home/kali/projects/pfc/pfc_frontend/node_modules/@hookform/resolvers/dist/resolvers.mjs:1
import{get as r,set as i}from"react-hook-form";var e=function(i,e,t){if(i&&"reportValidity"in i){var f=r(t,e);i.setCustomValidity(f&&f.message||""),i.reportValidity()}},t=function(r,i){var t=function(t){var f=i.fields[t];f&&f.ref&&"reportValidity"in f.ref?e(f.ref,t,r):f.refs&&f.refs.forEach(function(i){return e(i,t,r)})};for(var f in i.fields)t(f)},f=function(e,f){f.shouldUseNativeValidation&&t(e,f);var o={};for(var a in e){var n=r(f.fields,a);i(o,a,Object.assign(e[a],{ref:n&&n.ref}))}return o};export{f as toNestError,t as validateFieldsNatively};
                ^^^
SyntaxError: Named export 'set' not found. The requested module 'react-hook-form' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'react-hook-form';
const {get: r,set: i}from"react-hook-form";var e=function(i,e,t){if(i&&"reportValidity"in i){var f=r(t,e);i.setCustomValidity(f&&f.message||""),i.reportValidity()}},t=function(r,i){var t=function(t){var f=i.fields[t];f&&f.ref&&"reportValidity"in f.ref?e(f.ref,t,r):f.refs&&f.refs.forEach(function(i){return e(i,t,r)})};for(var f in i.fields)t(f)},f=function(e,f){f.shouldUseNativeValidation&&t(e,f);var o={};for(var a in e){var n=r(f.fields,a);i(o,a,Object.assign(e[a],{ref:n&&n.ref}))}return o};export{f: toNestError,t: validateFieldsNatively} = pkg;

    at ModuleJob._instantiate (internal/modules/esm/module_job.js:124:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:179:5)
    at async Loader.import (internal/modules/esm/loader.js:178:24) {
  type: 'SyntaxError'
}
```

**Comment by bluebill1049** [comment]
any update on this issue.

**Comment by evocateur** [comment]
I was able to build successfully on the latest version of Next (12.0.9 when I tried last week) and latest version of `@hookform/resolvers`. I suspect deeper issues are at play in this particular case.

**Comment by bluebill1049** [comment]
thanks @evocateur I think it's to do with @yangricardo specific setup instead a general issue.
