### ISSUE TITLE
Refactor Typebox resolver implementation to avoid Microbundle issue with Async generators

### ISSUE THREAD

**Issue by JacopoPatroclo** [react-hook-form/resolvers#536]
**Describe the bug**
When I use the Typebox resolver inside a Vite application an error is thrown I believe related to this issue
https://github.com/developit/microbundle/issues/873

The error in question is
```
typebox.ts:14 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'substring')
    at a (typebox.ts:14:24)
    at Object.resolver (typebox.ts:57:9)
    at _executeSchema (createFormControl.ts:382:14)
    at createFormControl.ts:1051:42
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:25)
    at executeDispatch (react-dom.development.js:9041:3)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9073:7)
```

**To Reproduce**
In the sandbox open the js console and click the submit button.

**Codesandbox link (Required)**
- [Typebox sandbox](https://codesandbox.io/p/sandbox/vite-react-ts-forked-nr1s92?file=%2Fvite.config.ts&selection=%5B%7B%22endColumn%22%3A47%2C%22endLineNumber%22%3A20%2C%22startColumn%22%3A47%2C%22startLineNumber%22%3A20%7D%5D)

**Expected behavior**
The error should not happen

**Comment by jorisre** [comment]
Hi @JacopoPatroclo, Thank you for reporting the issue. Here is the PR that fix it #537

**Comment by jorisre** [comment]
PR merge, the release will be available in a few minutes, can you try?

**Comment by JacopoPatroclo** [comment]
@jorisre worked like a charm. Thanks a lot for the quick response and the fantastic library.

Everyone who stumbles on this: use version `3.0.1` or above to solve this issue!
